# Generated by Django 6.0 on 2025-12-14 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 17, 11, 44, 6, 585467, tzinfo=datetime.timezone.utc)),
        ),
    ]
