# Generated by Django 6.0 on 2025-12-14 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 17, 12, 5, 53, 908941, tzinfo=datetime.timezone.utc)),
        ),
    ]
